// src/lib/components/AddProjectForm.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { goto } from '$app/navigation';

	let {
		action = '',
		errorMessage = '',
		onSuccess
	}: {
		action?: string;
		errorMessage?: string;
		onSuccess?: (slug: string) => void;
	} = $props();

	let pathValue = $state('');
	let submitting = $state(false);
	let localError = $state('');

	const canBrowse =
		typeof globalThis.window !== 'undefined' && 'showDirectoryPicker' in globalThis.window;

	function handleBrowse() {
		if (canBrowse) {
			(globalThis.window as any)
				.showDirectoryPicker()
				.then((handle: any) => {
					pathValue = handle.name;
				})
				.catch(() => {});
		}
	}

	$effect(() => {
		localError = errorMessage;
	});
</script>

<form
	method="POST"
	action={action || undefined}
	use:enhance={() => {
		submitting = true;
		localError = '';
		return async ({ result, update }) => {
			submitting = false;
			if (result.type === 'redirect') {
				await update();
			} else if (result.type === 'failure') {
				const data = result.data as Record<string, any>;
				localError = data?.error || data?.addProjectError || 'Unknown error';
			} else if (result.type === 'success') {
				const data = result.data as Record<string, any>;
				if (data?.addProjectSuccess && data?.newSlug) {
					onSuccess?.(data.newSlug);
				}
				await update();
			}
		};
	}}
>
	<div class="mb-4">
		<label for="project-path" class="mb-2 block text-sm font-medium"> Git Repository Path </label>
		<div class="flex gap-2">
			<input
				id="project-path"
				name="path"
				type="text"
				bind:value={pathValue}
				placeholder="/path/to/your/repo"
				class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
			/>
			{#if canBrowse}
				<button
					type="button"
					onclick={handleBrowse}
					class="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
				>
					Browse
				</button>
			{/if}
		</div>
	</div>

	{#if localError}
		<p class="mb-4 text-sm text-destructive">{localError}</p>
	{/if}

	<button
		type="submit"
		disabled={submitting || !pathValue.trim()}
		class="inline-flex h-10 w-full items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:pointer-events-none disabled:opacity-50"
	>
		{submitting ? 'Adding...' : 'Add Project'}
	</button>
</form>

// src/components/project/AddProjectForm.tsx
import { Show } from "solid-js";
import {
  createAddProjectController,
  type AddProjectController,
} from "./add-project-controller.js";
import BoardSelector from "./BoardSelector.js";

interface AddProjectFormProps {
  action: (
    path: string, branch: string, mainBranch: string, boardId: string,
  ) => Promise<{ projectSlug?: string; error?: string }>;
  errorMessage?: string;
  onSuccess?: (projectSlug: string) => void;
  submitTitle?: string;
  ctrl?: AddProjectController;
}

export default function AddProjectForm(props: AddProjectFormProps) {
  const s = props.ctrl ?? createAddProjectController({
    action: props.action,
    onSuccess: props.onSuccess,
    errorMessage: props.errorMessage,
  });

  return (
    <form onSubmit={s.handleSubmit}>
      <div class="mb-4">
        <label for="project-path" class="mb-2 block text-sm font-medium">Git Repository Path</label>
        <div class="flex gap-2">
          <input
            id="project-path"
            type="text"
            value={s.pathValue()}
            onInput={(e) => s.setPathValue(e.currentTarget.value)}
            placeholder="/path/to/your/repo"
            class="input"
            data-testid="add-project-path-input"
          />
          <button
            type="button"
            onClick={s.handleBrowsePath}
            class="btn-secondary"
            data-testid="add-project-path-browse"
          >Browse</button>
        </div>
      </div>
      <BoardSelector
        boardId={s.boardId}
        setBoardId={s.setBoardId}
        onError={s.setLocalError}
      />
      <div class="mb-4">
        <label for="project-main-branch" class="mb-2 block text-sm font-medium">Main branch</label>
        <input
          id="project-main-branch"
          type="text"
          value={s.mainBranchValue()}
          onInput={(e) => s.setMainBranchValue(e.currentTarget.value)}
          placeholder="Auto-detected from repository"
          class="input"
          data-testid="add-project-main-branch-input"
        />
      </div>
      <div class="mb-4">
        <label for="project-branch" class="mb-2 block text-sm font-medium">Tickets branch name</label>
        <input
          id="project-branch"
          type="text"
          value={s.branchValue()}
          onInput={(e) => s.setBranchValue(e.currentTarget.value)}
          placeholder="tickets"
          class="input"
          data-testid="add-project-branch-input"
        />
      </div>
      <Show when={s.localError()}><p class="mb-4 text-sm text-destructive">{s.localError()}</p></Show>
      <button
        type="submit"
        disabled={s.submitting() || !s.pathValue().trim()}
        title={props.submitTitle}
        class="btn-primary w-full"
        data-testid="add-project-submit"
      >
        Add Project
      </button>
    </form>
  );
}
