// src/lib/components/AddProjectForm.tsx
import { createSignal, Show } from "solid-js";

interface AddProjectFormProps {
  action: (path: string) => Promise<{ slug?: string; error?: string }>;
  errorMessage?: string;
  onSuccess?: (slug: string) => void;
}

export default function AddProjectForm(props: AddProjectFormProps) {
  const [pathValue, setPathValue] = createSignal("");
  const [submitting, setSubmitting] = createSignal(false);
  const [localError, setLocalError] = createSignal(props.errorMessage ?? "");

  const canBrowse =
    typeof globalThis.window !== "undefined" &&
    "showDirectoryPicker" in globalThis.window;

  async function handleBrowse() {
    if (canBrowse) {
      try {
        const handle = await (globalThis.window as any).showDirectoryPicker();
        setPathValue(handle.name);
      } catch {
        /* user cancelled */
      }
    }
  }

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    const trimmed = pathValue().trim();
    if (!trimmed) return;
    setSubmitting(true);
    setLocalError("");
    try {
      const result = await props.action(trimmed);
      if (result.error) {
        setLocalError(result.error);
      } else if (result.slug) {
        props.onSuccess?.(result.slug);
      }
    } catch (err: any) {
      setLocalError(err?.message ?? "Unknown error");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <div class="mb-4">
        <label for="project-path" class="mb-2 block text-sm font-medium">
          Git Repository Path
        </label>
        <div class="flex gap-2">
          <input
            id="project-path"
            type="text"
            value={pathValue()}
            onInput={(e) => setPathValue(e.currentTarget.value)}
            placeholder="/path/to/your/repo"
            class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
          />
          <Show when={canBrowse}>
            <button
              type="button"
              onClick={handleBrowse}
              class="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
            >
              Browse
            </button>
          </Show>
        </div>
      </div>

      <Show when={localError()}>
        <p class="mb-4 text-sm text-destructive">{localError()}</p>
      </Show>

      <button
        type="submit"
        disabled={submitting() || !pathValue().trim()}
        class="inline-flex h-10 w-full items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:pointer-events-none disabled:opacity-50"
      >
        {submitting() ? "Adding..." : "Add Project"}
      </button>
    </form>
  );
}

// src/lib/components/AddProjectForm.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { goto } from '$app/navigation';

	let {
		action = '',
		errorMessage = '',
		onSuccess
	}: {
		action?: string;
		errorMessage?: string;
		onSuccess?: (slug: string) => void;
	} = $props();

	let pathValue = $state('');
	let submitting = $state(false);
	let localError = $state('');

	const canBrowse =
		typeof globalThis.window !== 'undefined' && 'showDirectoryPicker' in globalThis.window;

	function handleBrowse() {
		if (canBrowse) {
			(globalThis.window as any)
				.showDirectoryPicker()
				.then((handle: any) => {
					pathValue = handle.name;
				})
				.catch(() => {});
		}
	}

	$effect(() => {
		localError = errorMessage;
	});
</script>

<form
	method="POST"
	action={action || undefined}
	use:enhance={() => {
		submitting = true;
		localError = '';
		return async ({ result, update }) => {
			submitting = false;
			if (result.type === 'redirect') {
				await update();
			} else if (result.type === 'failure') {
				const data = result.data as Record<string, any>;
				localError = data?.error || data?.addProjectError || 'Unknown error';
			} else if (result.type === 'success') {
				const data = result.data as Record<string, any>;
				if (data?.addProjectSuccess && data?.newSlug) {
					onSuccess?.(data.newSlug);
				}
				await update();
			}
		};
	}}
>
	<div class="mb-4">
		<label for="project-path" class="mb-2 block text-sm font-medium"> Git Repository Path </label>
		<div class="flex gap-2">
			<input
				id="project-path"
				name="path"
				type="text"
				bind:value={pathValue}
				placeholder="/path/to/your/repo"
				class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
			/>
			{#if canBrowse}
				<button
					type="button"
					onclick={handleBrowse}
					class="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
				>
					Browse
				</button>
			{/if}
		</div>
	</div>

	{#if localError}
		<p class="mb-4 text-sm text-destructive">{localError}</p>
	{/if}

	<button
		type="submit"
		disabled={submitting || !pathValue.trim()}
		class="inline-flex h-10 w-full items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:pointer-events-none disabled:opacity-50"
	>
		{submitting ? 'Adding...' : 'Add Project'}
	</button>
</form>
