// src/lib/components/TicketDetailDialog.svelte
<script lang="ts">
	import type { TicketInfo } from '$lib/types.js';
	import { Carta, MarkdownEditor } from 'carta-md';
	import 'carta-md/default.css';

	let {
		open = $bindable(false),
		slug,
		ticket,
		columns = []
	}: {
		open: boolean;
		slug: string;
		ticket: TicketInfo | null;
		columns: string[];
	} = $props();

	const carta = new Carta();

	let activeTab = $state('');
	let content = $state('');
	let savedContent = $state('');
	let loading = $state(false);
	let saving = $state(false);
	let confirmingClose = $state(false);

	$effect(() => {
		if (open && ticket && columns.length > 0) {
			activeTab = columns[0];
		}
	});

	$effect(() => {
		if (open && ticket && activeTab) {
			loadStage(activeTab);
		}
	});

	async function loadStage(stage: string) {
		if (!ticket) return;
		loading = true;
		content = '';
		try {
			const res = await fetch(
				`/api/projects/${slug}/board/tickets/${ticket.folderName}/stages/${stage}`
			);
			if (res.ok) {
				const data = await res.json();
				content = data.content;
			} else if (res.status === 404) {
				content = '';
			}
			savedContent = content;
		} catch {
			content = '';
			savedContent = '';
		} finally {
			loading = false;
		}
	}

	async function saveStage() {
		if (!ticket || !activeTab) return;
		saving = true;
		try {
			await fetch(
				`/api/projects/${slug}/board/tickets/${ticket.folderName}/stages/${activeTab}`,
				{
					method: 'PUT',
					headers: { 'Content-Type': 'application/json' },
					body: JSON.stringify({ content })
				}
			);
			savedContent = content;
		} catch {
			// swallow
		} finally {
			saving = false;
		}
	}

	function close() {
		if (content !== savedContent) {
			confirmingClose = true;
			return;
		}
		open = false;
	}

	function forceClose() {
		confirmingClose = false;
		open = false;
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			if (confirmingClose) {
				confirmingClose = false;
			} else {
				close();
			}
		}
	}
</script>

{#if open && ticket}
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div
		class="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
		onkeydown={handleKeydown}
	>
		<!-- svelte-ignore a11y_click_events_have_key_events -->
		<!-- svelte-ignore a11y_no_static_element_interactions -->
		<div class="fixed inset-0" onclick={close}></div>
		<div
			class="relative z-10 flex h-[80vh] w-full max-w-3xl flex-col rounded-lg border border-border bg-card shadow-lg"
		>
			<div class="border-b border-border p-4">
				<h2 class="text-lg font-semibold">
					{ticket.number} - {ticket.title}
				</h2>
			</div>

			<div class="flex border-b border-border">
				{#each columns as col}
					<button
						class="px-4 py-2 text-sm font-medium transition-colors {activeTab === col
							? 'border-b-2 border-primary text-foreground'
							: 'text-muted-foreground hover:text-foreground'}"
						onclick={() => (activeTab = col)}
					>
						{col}
					</button>
				{/each}
			</div>

			<div class="flex-1 overflow-hidden p-4">
				{#if loading}
					<div class="flex h-full items-center justify-center">
						<div
							class="h-6 w-6 animate-spin rounded-full border-2 border-muted-foreground border-t-transparent"
						></div>
					</div>
				{:else}
					<div class="carta-wrapper h-full">
						<MarkdownEditor {carta} bind:value={content} mode="tabs" placeholder="Write markdown here..." />
					</div>
				{/if}
			</div>

			<div class="flex justify-end gap-2 border-t border-border p-4">
				<button
					type="button"
					onclick={close}
					class="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
				>
					Close
				</button>
				<button
					type="button"
					onclick={saveStage}
					disabled={saving || loading || content === savedContent}
					class="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:pointer-events-none disabled:opacity-50"
				>
					{saving ? 'Saving...' : 'Save'}
				</button>
			</div>
		</div>
	</div>
{/if}

{#if confirmingClose}
	<div class="fixed inset-0 z-[60] flex items-center justify-center bg-black/50">
		<div class="relative z-10 w-full max-w-md rounded-lg border border-border bg-card p-6 shadow-lg">
			<h2 class="mb-4 text-lg font-semibold">Unsaved Changes</h2>
			<p class="mb-4 text-sm text-muted-foreground">
				You have unsaved changes. Discard them?
			</p>
			<div class="flex justify-end gap-2">
				<button
					type="button"
					onclick={() => (confirmingClose = false)}
					class="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
				>
					Cancel
				</button>
				<button
					type="button"
					onclick={forceClose}
					class="inline-flex h-10 items-center justify-center rounded-md bg-destructive px-4 py-2 text-sm font-medium text-destructive-foreground hover:bg-destructive/90"
				>
					Discard
				</button>
			</div>
		</div>
	</div>
{/if}

<style>
	.carta-wrapper :global(.carta-editor) {
		height: 100%;
	}
	.carta-wrapper :global(.carta-wrapper) {
		height: 100%;
		overflow: auto;
	}
	.carta-wrapper :global(.carta-container) {
		height: 100%;
	}
	.carta-wrapper :global(.carta-font-code) {
		font-family: monospace;
		font-size: 0.875rem;
	}
</style>

// src/lib/components/TicketDetailDialog.tsx
import { createSignal, createEffect, Show, For, on, onCleanup } from "solid-js";
import type { TicketInfo } from "~/lib/types.js";

function DiscardConfirmation(props: {
  open: boolean;
  message: string;
  onCancel: () => void;
  onDiscard: () => void;
}) {
  return (
    <Show when={props.open}>
      <div class="fixed inset-0 z-[60] flex items-center justify-center bg-black/50">
        <div class="relative z-10 w-full max-w-md rounded-lg border border-border bg-card p-6 shadow-lg">
          <h2 class="mb-4 text-lg font-semibold">Unsaved Changes</h2>
          <p class="mb-4 text-sm text-muted-foreground">{props.message}</p>
          <div class="flex justify-end gap-2">
            <button
              type="button"
              onClick={props.onCancel}
              class="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={props.onDiscard}
              class="inline-flex h-10 items-center justify-center rounded-md bg-destructive px-4 py-2 text-sm font-medium text-destructive-foreground hover:bg-destructive/90"
            >
              Discard
            </button>
          </div>
        </div>
      </div>
    </Show>
  );
}

interface TicketDetailDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  slug: string;
  ticket: TicketInfo | null;
  columns: string[];
}

export default function TicketDetailDialog(props: TicketDetailDialogProps) {
  const [activeTab, setActiveTab] = createSignal("");
  const [content, setContent] = createSignal("");
  const [savedContent, setSavedContent] = createSignal("");
  const [loading, setLoading] = createSignal(false);
  const [saving, setSaving] = createSignal(false);
  const [confirmingClose, setConfirmingClose] = createSignal(false);
  const [pendingTab, setPendingTab] = createSignal<string | null>(null);
  const [confirmingTabSwitch, setConfirmingTabSwitch] = createSignal(false);

  const hasUnsavedChanges = () => content() !== savedContent();

  // beforeunload guard
  function handleBeforeUnload(e: BeforeUnloadEvent) {
    if (hasUnsavedChanges()) {
      e.preventDefault();
    }
  }

  createEffect(() => {
    if (props.open && typeof window !== "undefined") {
      window.addEventListener("beforeunload", handleBeforeUnload);
    } else if (typeof window !== "undefined") {
      window.removeEventListener("beforeunload", handleBeforeUnload);
    }
  });

  onCleanup(() => {
    if (typeof window !== "undefined") {
      window.removeEventListener("beforeunload", handleBeforeUnload);
    }
  });

  // Initialize active tab when dialog opens
  createEffect(
    on(
      () => [props.open, props.ticket, props.columns] as const,
      ([open, ticket, columns]) => {
        if (open && ticket && columns.length > 0) {
          setActiveTab(columns[0]);
        }
      }
    )
  );

  // Load stage content when tab changes
  createEffect(
    on(
      () => [props.open, props.ticket, activeTab()] as const,
      async ([open, ticket, tab]) => {
        if (!open || !ticket || !tab) return;
        setLoading(true);
        setContent("");
        try {
          const res = await fetch(
            `/api/projects/${props.slug}/board/tickets/${ticket.folderName}/stages/${tab}`
          );
          if (res.ok) {
            const data = await res.json();
            setContent(data.content);
            setSavedContent(data.content);
          } else {
            setContent("");
            setSavedContent("");
          }
        } catch {
          setContent("");
          setSavedContent("");
        } finally {
          setLoading(false);
        }
      }
    )
  );

  async function saveStage() {
    const ticket = props.ticket;
    const tab = activeTab();
    if (!ticket || !tab) return;
    setSaving(true);
    try {
      await fetch(
        `/api/projects/${props.slug}/board/tickets/${ticket.folderName}/stages/${tab}`,
        {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ content: content() }),
        }
      );
      setSavedContent(content());
    } catch {
      // swallow
    } finally {
      setSaving(false);
    }
  }

  function requestTabSwitch(tab: string) {
    if (tab === activeTab()) return;
    if (hasUnsavedChanges()) {
      setPendingTab(tab);
      setConfirmingTabSwitch(true);
      return;
    }
    setActiveTab(tab);
  }

  function confirmTabSwitch() {
    const tab = pendingTab();
    setConfirmingTabSwitch(false);
    setPendingTab(null);
    if (tab) {
      setActiveTab(tab);
    }
  }

  function cancelTabSwitch() {
    setConfirmingTabSwitch(false);
    setPendingTab(null);
  }

  function close() {
    if (hasUnsavedChanges()) {
      setConfirmingClose(true);
      return;
    }
    props.onOpenChange(false);
  }

  function forceClose() {
    setConfirmingClose(false);
    props.onOpenChange(false);
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") {
      if (confirmingTabSwitch()) {
        cancelTabSwitch();
      } else if (confirmingClose()) {
        setConfirmingClose(false);
      } else {
        close();
      }
    }
  }

  return (
    <>
      <Show when={props.open && props.ticket}>
        <div
          class="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
          onKeyDown={handleKeydown}
        >
          <div class="fixed inset-0" onClick={close} />
          <div class="relative z-10 flex h-[80vh] w-full max-w-3xl flex-col rounded-lg border border-border bg-card shadow-lg">
            <div class="border-b border-border p-4">
              <h2 class="text-lg font-semibold">
                {props.ticket!.number} - {props.ticket!.title}
              </h2>
            </div>

            <div class="flex border-b border-border">
              <For each={props.columns}>
                {(col) => (
                  <button
                    class={`px-4 py-2 text-sm font-medium transition-colors ${
                      activeTab() === col
                        ? "border-b-2 border-primary text-foreground"
                        : "text-muted-foreground hover:text-foreground"
                    }`}
                    onClick={() => requestTabSwitch(col)}
                  >
                    {col}
                  </button>
                )}
              </For>
            </div>

            <div class="flex-1 overflow-hidden p-4">
              <Show
                when={!loading()}
                fallback={
                  <div class="flex h-full items-center justify-center">
                    <div class="h-6 w-6 animate-spin rounded-full border-2 border-muted-foreground border-t-transparent" />
                  </div>
                }
              >
                <textarea
                  value={content()}
                  onInput={(e) => setContent(e.currentTarget.value)}
                  class="h-full w-full resize-none rounded-md border border-input bg-background p-3 font-mono text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                  placeholder="Write markdown here..."
                />
              </Show>
            </div>

            <div class="flex justify-end gap-2 border-t border-border p-4">
              <button
                type="button"
                onClick={close}
                class="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
              >
                Close
              </button>
              <button
                type="button"
                onClick={saveStage}
                disabled={saving() || loading() || !hasUnsavedChanges()}
                class="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:pointer-events-none disabled:opacity-50"
              >
                {saving() ? "Saving..." : "Save"}
              </button>
            </div>
          </div>
        </div>
      </Show>

      {/* Unsaved changes confirmation dialog (close) */}
      <DiscardConfirmation
        open={confirmingClose()}
        message="You have unsaved changes. Discard them?"
        onCancel={() => setConfirmingClose(false)}
        onDiscard={forceClose}
      />

      {/* Unsaved changes confirmation dialog (tab switch) */}
      <DiscardConfirmation
        open={confirmingTabSwitch()}
        message="You have unsaved changes. Discard them and switch tabs?"
        onCancel={cancelTabSwitch}
        onDiscard={confirmTabSwitch}
      />
    </>
  );
}
