// src/components/ticket/TicketCard.tsx
import { Show, For } from "solid-js";
import EllipsisVertical from "lucide-solid/icons/ellipsis-vertical";
import { MenuRoot, MenuTrigger, MenuContent, MenuItem, MenuSeparator } from "../ui/menu";
import type { TicketInfo } from "~/core/ticket/ticket-store.js";
import type { SwatchColumn } from "~/core/board/status-swatch.js";
import HerdrStatusIcon from "./HerdrStatusIcon";
import { useHerdrStatuses } from "./herdr-statuses-context.js";
import { useShortcutRunner } from "../board/shortcut-runner-context.js";

interface TicketCardProps {
  ticket: TicketInfo;
  orphanedStatus?: string;
  columns: SwatchColumn[];
  onDelete: (ticket: TicketInfo) => void;
  onArchive: (ticket: TicketInfo) => void;
  onViewDetail: (ticket: TicketInfo) => void;
}

export default function TicketCard(props: TicketCardProps) {
  const herdrStatus = useHerdrStatuses();
  const shortcutRunner = useShortcutRunner();
  function handleCardClick(e: MouseEvent) {
    if ((e.target as HTMLElement).closest("[data-menu]")) return;
    props.onViewDetail(props.ticket);
  }

  return (
    <div
      data-drag-source
      data-testid="kanban-board-ticket-card"
      data-folder-name={props.ticket.folderName}
      class="ticket-card cursor-pointer rounded-md bg-card p-3 transition-colors hover:bg-accent"
      onClick={handleCardClick}
    >
      <div class="mb-1 flex items-start justify-between">
        <div class="flex min-w-0 items-center gap-1.5">
          <span class="label-mono font-medium text-primary">{props.ticket.number}</span>
          <Show when={herdrStatus(props.ticket.folderName)}>
            {(s) => <HerdrStatusIcon status={s()} />}
          </Show>
        </div>
        <div data-menu class="-mr-2 -mt-2">
          <MenuRoot
            trigger={
              <MenuTrigger
                class="btn-ghost-icon size-8"
                aria-label="Ticket actions"
                data-testid="kanban-board-ticket-menu-trigger"
                onClick={(e: MouseEvent) => e.stopPropagation()}
              >
                <EllipsisVertical size={20} />
              </MenuTrigger>
            }
          >
            <MenuContent>
              <MenuItem
                value="archive"
                data-testid="kanban-board-ticket-menu-archive"
                onClick={(e: MouseEvent) => {
                  e.stopPropagation(); props.onArchive(props.ticket);
                }}
              >Archive</MenuItem>
              <MenuItem
                value="delete"
                class="text-destructive"
                data-testid="kanban-board-ticket-menu-delete"
                onClick={(e: MouseEvent) => {
                  e.stopPropagation(); props.onDelete(props.ticket);
                }}
              >Delete</MenuItem>
              <Show when={(shortcutRunner?.shortcuts().length ?? 0) > 0}>
                <MenuSeparator />
                <For each={shortcutRunner!.shortcuts()}>
                  {(shortcut) => (
                    <MenuItem
                      value={`shortcut-${shortcut.name}`}
                      data-testid="kanban-board-ticket-menu-shortcut"
                      data-shortcut-name={shortcut.name}
                      disabled={shortcutRunner!.running() !== ""}
                      onClick={(e: MouseEvent) => {
                        e.stopPropagation();
                        shortcutRunner!.run(props.ticket, shortcut.name);
                      }}
                    >{shortcut.name}</MenuItem>
                  )}
                </For>
              </Show>
            </MenuContent>
          </MenuRoot>
        </div>
      </div>
      <p class="line-clamp-2 text-sm">{props.ticket.title}</p>
      {props.orphanedStatus && (
        <p class="mt-1 text-xs text-destructive" data-testid="kanban-board-ticket-orphaned-status">
          {props.orphanedStatus}
        </p>
      )}
    </div>
  );
}

// src/lib/components/TicketCard.svelte
<script lang="ts">
	import type { TicketInfo } from '$lib/types.js';

	let {
		ticket,
		columns = [],
		onEdit,
		onDelete,
		onClick,
		onMoveTo
	}: {
		ticket: TicketInfo;
		columns: string[];
		onEdit: (ticket: TicketInfo) => void;
		onDelete: (ticket: TicketInfo) => void;
		onClick: (ticket: TicketInfo) => void;
		onMoveTo: (ticket: TicketInfo, status: string) => void;
	} = $props();

	let menuOpen = $state(false);
	let moveMenuOpen = $state(false);

	const stageColors = [
		'bg-blue-100 text-blue-800',
		'bg-green-100 text-green-800',
		'bg-yellow-100 text-yellow-800',
		'bg-purple-100 text-purple-800',
		'bg-pink-100 text-pink-800'
	];

	function getStageColor(index: number): string {
		return stageColors[index % stageColors.length];
	}

	function handleCardClick(e: MouseEvent) {
		const target = e.target as HTMLElement;
		if (target.closest('[data-menu]')) return;
		onClick(ticket);
	}

	function handleMenuClick(e: MouseEvent) {
		e.stopPropagation();
		menuOpen = !menuOpen;
		moveMenuOpen = false;
	}
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
	class="cursor-pointer rounded-md border border-border bg-card p-3 shadow-sm transition-shadow hover:shadow-md"
	onclick={handleCardClick}
>
	<div class="mb-1 flex items-start justify-between">
		<span class="text-sm font-medium text-primary">{ticket.number}</span>
		<div class="relative" data-menu>
			<button
				class="rounded p-1 text-muted-foreground hover:bg-accent hover:text-accent-foreground"
				onclick={handleMenuClick}
				aria-label="Ticket actions"
			>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					width="16"
					height="16"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				>
					<circle cx="12" cy="12" r="1" />
					<circle cx="12" cy="5" r="1" />
					<circle cx="12" cy="19" r="1" />
				</svg>
			</button>
			{#if menuOpen}
				<!-- svelte-ignore a11y_click_events_have_key_events -->
				<!-- svelte-ignore a11y_no_static_element_interactions -->
				<div class="fixed inset-0 z-40" onclick={() => { menuOpen = false; moveMenuOpen = false; }}></div>
				<div
					class="absolute right-0 z-50 min-w-[150px] rounded-md border border-border bg-popover py-1 shadow-md"
				>
					<div class="relative">
						<button
							class="w-full px-3 py-2 text-left text-sm hover:bg-accent hover:text-accent-foreground"
							onclick={(e) => {
								e.stopPropagation();
								moveMenuOpen = !moveMenuOpen;
							}}
						>
							Move to...
						</button>
						{#if moveMenuOpen}
							<div
								class="absolute left-full top-0 min-w-[120px] rounded-md border border-border bg-popover py-1 shadow-md"
							>
								{#each columns.filter((c) => c !== ticket.status) as col}
									<button
										class="w-full px-3 py-2 text-left text-sm hover:bg-accent hover:text-accent-foreground"
										onclick={(e) => {
											e.stopPropagation();
											menuOpen = false;
											moveMenuOpen = false;
											onMoveTo(ticket, col);
										}}
									>
										{col}
									</button>
								{/each}
							</div>
						{/if}
					</div>
					<button
						class="w-full px-3 py-2 text-left text-sm hover:bg-accent hover:text-accent-foreground"
						onclick={(e) => {
							e.stopPropagation();
							menuOpen = false;
							onEdit(ticket);
						}}
					>
						Edit
					</button>
					<button
						class="w-full px-3 py-2 text-left text-sm text-destructive hover:bg-accent"
						onclick={(e) => {
							e.stopPropagation();
							menuOpen = false;
							onDelete(ticket);
						}}
					>
						Delete
					</button>
				</div>
			{/if}
		</div>
	</div>
	<p class="line-clamp-2 text-sm">{ticket.title}</p>
	{#if ticket.stageNames.length > 0}
		<div class="mt-2 flex flex-wrap gap-1">
			{#each ticket.stageNames as stage, i}
				<span class="rounded-full px-2 py-0.5 text-xs {getStageColor(i)}">
					{stage}
				</span>
			{/each}
		</div>
	{/if}
</div>
